### ISSUE TITLE
tutorial doesn't seem to work for other brain regions

### ISSUE THREAD

**Issue by nikparth** [serre-lab/neural_harmonizer#1]
Hi! 

Thanks for the starter tutorial- it seems to work great for the george_central_it but seem so to break for the red_central_it and george_posterior_it. I think the posterior_it issue is just that there is a hard-coded "30" in the neural_benchmark for the resizing but the number of neurons for the other regions is not 30 so that is an easy fix. The red_central_it however, still does not work which I think has to do with the grid_size being 9x9 vs 17x17 and there being some issues with the reducer (in the metrics.py)? If you could look into this that would be great! 

If you could have the tutorial just produce the same numbers as the paper main-text for the 3 regions and the example harmonized resnet that would be awesome! 

Thank you,
Nikhil

**Comment by nikparth** [comment]
Adding some more notes to possibly look at to fix consistency with the paper. The paper states "We
measured DNN neuronal fits as the Spearman correlations between model predictions and true neural
responses for each patch of an image held out of training divided by each neuron’s noise ceiling. We
then stored the median Spearman correlation over neurons and repeated the training/testing procedure
to get the mean correlation across all images viewed by a monkey." Right now, the code is measuring the fits using the _pearson correlation_ not spearman and aggregates with the mean and not the median so there are inconsistencies. Also I am confused about the current implementation of the ceiling_score function as it uses a spearman similarity rather than simply calculating the ceiling as described in the paper (maximum correlation between a neuron and any other neuron for that image).

**Comment by piperod** [comment]
Thank you so much for providing feedback and using the code! Sorry for the delay. I push a fix for the grid problem and fix the ceiling score. Added comments to make sure is clear the process we performed. Thank you also for pointing the discrepancies with the paper, I provided support for both spearman and pearson correlations. As well, added optional reducer for mean and median. 

I will push next week our results and plotting functions to ease reproducibility. Thank you again for the feedback. Please let us know if you run into any other issue.
